workspace: "/tmp/"
ccf_ver: "0.15.2"
ccf_tarball: "ccf.tar.gz"
ccf_suffix: "{{ 'latest/download' if ccf_ver == 'latest' else 'download/ccf-' + ccf_ver }}"
ccf_url: "https://github.com/microsoft/CCF/releases/{{ ccf_suffix }}/{{ ccf_tarball }}"
ccf_prefix: "/opt/openenclave"
