- name: Include vars
  include_vars: common.yml

- name: Add LLVM repository key
  apt_key:
    url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
    state: present
  become: yes

- name: Add LLVM repository
  apt_repository:
    repo: "deb http://apt.llvm.org/{{ ansible_distribution_release }} llvm-toolchain-{{ ansible_distribution_release }}-{{ llvm_version }} main"
    state: present
    update_cache: yes
  become: yes
