steps:
  - script: |
      cmake -L .. 2>/dev/null | grep CMAKE_INSTALL_PREFIX: | cut -d = -f 2 > /tmp/install_prefix
      cpack -V -G DEB
      PKG=`ls *.deb`
      cp $PKG $(Build.ArtifactStagingDirectory)
      echo "##vso[task.setvariable variable=pkgname]$PKG"
    workingDirectory: build
    displayName: "Make .deb package"

  - script: |
      python3.8 -m venv env
      source ./env/bin/activate
      pip install -r requirements.txt
      pip install wheel
      python setup.py bdist_wheel
      WHL=`ls dist/*.whl`
      cp $WHL $(Build.ArtifactStagingDirectory)
      WHL=`basename $WHL`
      echo "##vso[task.setvariable variable=wheel]$WHL"
    workingDirectory: python
    displayName: Build wheel

  - script: |
      sudo apt -y install ./$(pkgname)
      cat /tmp/install_prefix | xargs -i bash -c "PYTHON_PACKAGE_PATH=../python ./test_install.sh {}"
    workingDirectory: build
    displayName: Test installed CCF

  - script: |
      ./tests/test_install_build.sh
    displayName: Test building a sample against installed CCF

  - task: PublishPipelineArtifact@1
    inputs:
      path: $(Build.ArtifactStagingDirectory)/$(pkgname)
      artifact: $(pkgname)
      displayName: "Publish CCF Debian Package"

  - task: PublishPipelineArtifact@1
    inputs:
      path: $(Build.ArtifactStagingDirectory)/$(wheel)
      artifact: $(wheel)
      displayName: "Publish CCF Wheel"
